
site_name: BD - Bases de Datos
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate

  copyright: Licenciado bajo la licencia Creative Commons by-nc-nd

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
nav:
  
  - SQL - POSTGRES:
    - Resultados de Aprendizaje y Criterios de Evalucación: RA_CE.md
    - Objetivos: BD_PostgreSQL_DQL/objectius_i_coneixements_previs.md
    - 1. Introducción: BD_PostgreSQL_DQL/1_introducci.md
    - 2. DBeaver: BD_PostgreSQL_DQL/2_client_dbeaver_installaci_i_confiuraci.md
    - 3 Datos de los ejemplos y los ejercicios: BD_PostgreSQL_DQL/3_dades_dels_exemples_i_els_exercicis.md
    - 4. Operadores y Funciones de Postgres:
      - 4.1. Operadores: BD_PostgreSQL_DQL/6_operadors.md
      - 4.2. Funciones: BD_PostgreSQL_DQL/7_funcions.md
  - DQL - Consultas (parte I):  
      - Presentación Tema 4 (Parte 1): BD_PostgreSQL_DQL/0_presentacion.md
      - 1. La consulta SELECT: BD_PostgreSQL_DQL/1_la_consulta_select.md
      - 2. Consulta básica: BD_PostgreSQL_DQL/2_consulta_bsica.md
      - 3. Alias en las columnas: BD_PostgreSQL_DQL/3_lies_en_les_columnes.md
      - 4. La cláusula WHERE: BD_PostgreSQL_DQL/4_la_clusula_where.md       
      - 5. Funciones de agregado: BD_PostgreSQL_DQL/5_funcions_dagregat.md     
      - 6. La cláusula GROUP BY: BD_PostgreSQL_DQL/6_la_clusula_group_by.md      
      - 7. La cláusula HAVING: BD_PostgreSQL_DQL/7_la_clusula_having.md    
      - 8. La cláusula ORDER BY: BD_PostgreSQL_DQL/8_la_clusula_order_by.md 
      - 9. El predicado DISTINCT: BD_PostgreSQL_DQL/9_el_predicat_distinct.md  
      - 10. La cláusula LIMIT .. OFFSET: BD_PostgreSQL_DQL/10_la_clusula_limit__offset.md  
      - 11. Consulta de creación de tablas: BD_PostgreSQL_DQL/11_consulta_de_creaci_de_taules.md
      - 12. Orden en el que se ejecuta una sentencia SQL: BD_PostgreSQL_DQL/12_ordre_amb_qu_sexecuta_una_sentncia_sql.md
      - Ejercicios con los resultados (parte I): BD_PostgreSQL_DQL/exercicis_de_tot_el_tema_amb_els_resultats.md 
      - Ejemplos de BDs: BD_PostgreSQL_DQL/ejemplos_bd.md   
  - DQL - Consultas avanzadas (parte II):
      - Presentación Tema 4 (Parte 2): BD_PostgreSQL_DQL_Avancat/20_presentacion.md
      - 1. Introducción: BD_PostgreSQL_DQL_Avancat/21_introducci.md
      - 2. Combinaciones de tablas: BD_PostgreSQL_DQL_Avancat/22_combinacions_de_taules.md
      - 3. Subconsultas: BD_PostgreSQL_DQL_Avancat/23_subconsultes.md
      - 4. Consultas de operaciones de conjuntos: BD_PostgreSQL_DQL_Avancat/24_consultes_doperacions_de_conjunts.md  
      - Ejercicios con los resultados (parte II): BD_PostgreSQL_DQL_Avancat/exercicis_de_tot_el_tema_amb_els_resultats.md
  - DDL - Creación de Tablas:
      - 1. Introducción: BD_PostgreSQL_DDL/1_introducci.md
      - 2. DDL: BD_PostgreSQL_DDL/2_ddl.md
      - Ejercicios de todo el tema: BD_PostgreSQL_DDL/exercicis_de_tot_el_tema.md
  - DML - Manipulación de Datos:
      - 1. Introducción: BD_PostgreSQL_DML/1_introducci.md
      - 2. Consultas de actualización (DML): BD_PostgreSQL_DML/2_consultes_dactualitzaci.md
      - Ejercicios de todo el tema: BD_PostgreSQL_DML/exercicis_de_tot_el_tema.md
